// extracted from items.json — unique keys found across all item stats

/** @type {Record<string, string>} registry: camelCase → original stat label */
export const statKeys = {
	percentStrongerAgainstDark: '% stronger against Dark',
	percentStrongerAgainstEarth: '% stronger against Earth',
	percentStrongerAgainstFire: '% stronger against Fire',
	percentStrongerAgainstLight: '% stronger against Light',
	percentStrongerAgainstNeutral: '% stronger against Neutral',
	percentStrongerAgainstWater: '% stronger against Water',
	percentStrongerAgainstWind: '% stronger against Wind',
	agi: 'AGI',
	agiPercent: 'AGI %',
	aspd: 'ASPD',
	aspdPercent: 'ASPD %',
	atk: 'ATK',
	atkPercent: 'ATK %',
	atkDownAgiPercent: 'ATK DOWN (AGI %)',
	atkDownDexPercent: 'ATK DOWN (DEX %)',
	atkDownStrPercent: 'ATK DOWN (STR %)',
	atkDownVitPercent: 'ATK DOWN (VIT %)',
	atkUpAgiPercent: 'ATK UP (AGI %)',
	atkUpDexPercent: 'ATK UP (DEX %)',
	atkUpIntPercent: 'ATK UP (INT %)',
	atkUpStrPercent: 'ATK UP (STR %)',
	atkUpVitPercent: 'ATK UP (VIT %)',
	absoluteAccuracyPercent: 'Absolute Accuracy %',
	absoluteDodgePercent: 'Absolute Dodge %',
	accuracy: 'Accuracy',
	accuracyPercent: 'Accuracy %',
	add1SlotToA0SlottedKatana: 'Add 1 slot to a 0-slotted Katana',
	additionalMagicPercent: 'Additional Magic %',
	additionalMeleePercent: 'Additional Melee %',
	adds1SlotToA1SlottedAdditionalGear: 'Adds 1 slot to a 1-slotted additional gear',
	adds1SlotToA1SlottedArmor: 'Adds 1 slot to a 1-slotted armor',
	adds1SlotToA1SlottedSpecialGear: 'Adds 1 slot to a 1-slotted special gear',
	aggroPercent: 'Aggro %',
	ailmentResistancePercent: 'Ailment Resistance %',
	anticipatePercent: 'Anticipate %',
	attackMpRecovery: 'Attack MP Recovery',
	attackMpRecoveryPercent: 'Attack MP Recovery %',
	attackRangeM: 'Attack Range (m)',
	barrierCooldownPercent: 'Barrier Cooldown %',
	baseAtk: 'Base ATK',
	baseDef: 'Base DEF',
	baseDropRatePercent: 'Base Drop Rate %',
	baseStabilityPercent: 'Base Stability %',
	cspd: 'CSPD',
	cspdPercent: 'CSPD %',
	canFormAGuildOnce: 'Can form a guild once',
	canReSelectPersonalStatTheStatPointsDistributedToThePersonalStatWillBeReset:
		'Can re-select personal stat. The stat points distributed to the personal stat will be reset.',
	criticalDamage: 'Critical Damage',
	criticalDamagePercent: 'Critical Damage %',
	criticalRate: 'Critical Rate',
	criticalRatePercent: 'Critical Rate %',
	def: 'DEF',
	defPercent: 'DEF %',
	dex: 'DEX',
	dexPercent: 'DEX %',
	damageFromBossPercent: 'Damage from Boss %',
	damageToBossPercent: 'Damage to Boss %',
	darkElement: 'Dark Element',
	darkResistancePercent: 'Dark resistance %',
	deletesASkillTreeAndResetsTheSkillPoints: 'Deletes a skill tree and resets the skill points',
	deletesAllTheSkillTreesAndResetsTheSkillPoints:
		'Deletes all the skill trees and resets the skill points',
	dodge: 'Dodge',
	dodgePercent: 'Dodge %',
	dropRatePercent: 'Drop Rate %',
	expGainPercent: 'EXP Gain %',
	earthElement: 'Earth Element',
	earthResistancePercent: 'Earth resistance %',
	equipmentLostWhenFailed: 'Equipment lost when failed',
	evasionRechargePercent: 'Evasion Recharge %',
	fireElement: 'Fire Element',
	fireResistancePercent: 'Fire resistance %',
	flinchUnavailable: 'Flinch Unavailable',
	fractionalBarrierPercent: 'Fractional Barrier %',
	gemDustDropAmountPercent: 'Gem Dust Drop Amount %',
	gives100OrbShards: 'Gives 100 Orb Shards',
	givesRandomItemsZellBagspomRefine: 'Gives random items: Zell Bag(s)/Pom Refine',
	grants1To3TypesOfAbilitiesToAnAvatarItemTheSameAbilitiesWillNotBeGranted:
		'Grants 1 to 3 types of abilities to an avatar item. The same abilities will not be granted.',
	guardBreakPercent: 'Guard Break %',
	guardPowerPercent: 'Guard Power %',
	guardRechargePercent: 'Guard Recharge %',
	hp: 'HP',
	hpPercent: 'HP %',
	int: 'INT',
	intPercent: 'INT %',
	ignoresTheResurrectionTime: 'Ignores the resurrection time',
	invincibleAidSec: 'Invincible Aid (sec)',
	itemCooldown: 'Item Cooldown',
	learnBareHandSkillLv1: 'Learn Bare Hand Skill Lv 1',
	learnDancerSkillLv1: 'Learn Dancer Skill Lv 1',
	learnDarkPowerSkillLv1: 'Learn Dark Power Skill Lv1',
	learnMagicBladeSkillLv1: 'Learn Magic Blade Skill Lv1',
	learnMinstrelSkillLv1: 'Learn Minstrel Skill Lv 1',
	learnNinjaSkillLv1: 'Learn Ninja Skill Lv1',
	lightElement: 'Light Element',
	lightResistancePercent: 'Light resistance %',
	longRangeDamagePercent: 'Long Range Damage %',
	matk: 'MATK',
	matkPercent: 'MATK %',
	matkDownDexPercent: 'MATK DOWN (DEX %)',
	matkDownStrPercent: 'MATK DOWN (STR %)',
	matkDownVitPercent: 'MATK DOWN (VIT %)',
	matkUpAgiPercent: 'MATK UP (AGI %)',
	matkUpDexPercent: 'MATK UP (DEX %)',
	matkUpIntPercent: 'MATK UP (INT %)',
	matkUpStrPercent: 'MATK UP (STR %)',
	matkUpVitPercent: 'MATK UP (VIT %)',
	mdef: 'MDEF',
	mdefPercent: 'MDEF %',
	mp: 'MP',
	mpPercent: 'MP %',
	magicBarrier: 'Magic Barrier',
	magicPiercePercent: 'Magic Pierce %',
	magicResistancePercent: 'Magic Resistance %',
	manaElement: 'Mana Element',
	maxHp: 'MaxHP',
	maxHpPercent: 'MaxHP %',
	maxMp: 'MaxMP',
	maxMpPercent: 'MaxMP %',
	motionSpeedPercent: 'Motion Speed %',
	naturalHpRegen: 'Natural HP Regen',
	naturalHpRegenPercent: 'Natural HP Regen %',
	naturalMpRegen: 'Natural MP Regen',
	naturalMpRegenPercent: 'Natural MP Regen %',
	neutralResistancePercent: 'Neutral Resistance %',
	permanentlyUnlockAUniqueEmotion: 'Permanently unlock a unique emotion',
	petExpPercent: 'Pet EXP %',
	physicalBarrier: 'Physical Barrier',
	physicalPiercePercent: 'Physical Pierce %',
	physicalResistancePercent: 'Physical Resistance %',
	potential: 'Potential',
	preventsAilmentOnceInvalidAgainstImmobilization:
		'Prevents ailment once. Invalid against immobilization.',
	preventsDegradationPercent: 'Prevents degradation %',
	recoilPercent: 'Recoil %',
	reduceDmgBowlingPercent: 'Reduce Dmg (Bowling) %',
	reduceDmgBulletPercent: 'Reduce Dmg (Bullet) %',
	reduceDmgChargePercent: 'Reduce Dmg (Charge) %',
	reduceDmgFloorPercent: 'Reduce Dmg (Floor) %',
	reduceDmgFoeEpicenterPercent: 'Reduce Dmg (Foe Epicenter) %',
	reduceDmgMeteorPercent: 'Reduce Dmg (Meteor) %',
	reduceDmgPlayerEpicenterPercent: 'Reduce Dmg (Player Epicenter) %',
	reduceDmgStraightLinePercent: 'Reduce Dmg (Straight Line) %',
	reduceExplosionPercent: 'Reduce Explosion %',
	reduceVortexPercent: 'Reduce Vortex %',
	refineSuccessRatePercent: 'Refine Success Rate %',
	refineSuccessRatePercentFlat: 'Refine Success Rate % (flat)',
	reflectPercent: 'Reflect %',
	resetTheStatPointsDistributed: 'Reset the stat points distributed',
	reviveTimePercent: 'Revive Time %',
	str: 'STR',
	strPercent: 'STR %',
	safelyDetachesACrystalOnEquipment: 'Safely detaches a crystal on equipment',
	shortRangeDamagePercent: 'Short Range Damage %',
	stabilityPercent: 'Stability %',
	stunUnavailable: 'Stun Unavailable',
	teleportToNaiata: 'Teleport To Naiata',
	teleportToAncientEmpressTomb: "Teleport to Ancient Empress' Tomb",
	teleportToDikkitSector: 'Teleport to Dikkit Sector',
	teleportToEinklang: 'Teleport to Einklang',
	teleportToElScaro: 'Teleport to El Scaro',
	teleportToEthosFortress: 'Teleport to Ethos Fortress',
	teleportToGardenOfBeginning: 'Teleport to Garden of Beginning',
	teleportToGardenOfIceAndSnow: 'Teleport to Garden of Ice & Snow',
	teleportToHoraDiomedea: 'Teleport to Hora Diomedea',
	teleportToInjeVillage: 'Teleport to Inje Village',
	teleportToNovSaterica: 'Teleport to Nov Saterica',
	teleportToPersimmonCorynForest: 'Teleport to Persimmon Coryn Forest',
	teleportToRokokoPlains: 'Teleport to Rokoko Plains',
	teleportToRugioRuins: 'Teleport to Rugio Ruins',
	teleportToSofyaCity: 'Teleport to Sofya City',
	teleportToAMysteriousPlaceWhereYouCanGetColoredWeapons:
		'Teleport to a mysterious place where you can get colored weapons',
	teleportToTheDarkManor: 'Teleport to the Dark Manor',
	teleportToTheLastTownYouVisited: 'Teleport to the last town you visited',
	teleportToTheMapThatYouSelectOnWorldMap: 'Teleport to the map that you select on World Map',
	thrustResistancePercent: 'Thrust Resistance %',
	tumbleUnavailable: 'Tumble Unavailable',
	unsheatheAttack: 'Unsheathe Attack',
	unsheatheAttackPercent: 'Unsheathe Attack %',
	upgradeFor: 'Upgrade for',
	vit: 'VIT',
	vitPercent: 'VIT %',
	waterElement: 'Water Element',
	waterResistancePercent: 'Water resistance %',
	weaponAtk: 'Weapon ATK',
	weaponAtkPercent: 'Weapon ATK %',
	whenSucceedOnRefiningItemsRefinementBecomes:
		"When succeed on refining, item's refinement becomes",
	windElement: 'Wind Element',
	windResistancePercent: 'Wind resistance %'
};

/** @type {string[]} all original stat labels */
export const allStatKeys = Object.values(statKeys);

/** @type {string[]} all camelCase stat keys */
export const allStatKeyNames = Object.keys(statKeys);

// ===== exclusive conditions =====
// aligned with itemTypes naming where possible, extra: Heavy Armor, Light Armor, Dual Swords, Event

/** @type {Record<string, string>} registry: camelCase → original condition label */
export const exclusiveConditions = {
	oneHandedSword: '1-Handed Sword',
	twoHandedSword: '2-Handed Sword',
	additional: 'Additional Gear',
	armor: 'Armor',
	arrow: 'Arrow',
	bow: 'Bow',
	bowgun: 'Bowgun',
	bowgunBow: 'Bowgun,Bow',
	dagger: 'Dagger',
	dualSwords: 'Dual Swords',
	event: 'Event',
	halberd: 'Halberd',
	heavyArmor: 'Heavy Armor',
	heavyArmorLightArmor: 'Heavy Armor,Light Armor',
	katana: 'Katana',
	knuckles: 'Knuckle',
	knuckleMagicDeviceStaffBowgunBow2HandedSword1HandedSword:
		'Knuckle,Magic Device,Staff,Bowgun,Bow,2-Handed Sword,1-Handed Sword',
	lightArmor: 'Light Armor',
	magicDevice: 'Magic Device',
	magicDeviceDagger: 'Magic Device,Dagger',
	ninjutsuScroll: 'Ninjutsu Scroll',
	shield: 'Shield',
	special: 'Special Gear',
	staff: 'Staff'
};

// ===== exclusive keys =====
/** @type {string[]} all keys appearing in stats.exclusive[].stats */
export const exclusiveKeys = [
	'% stronger against Fire',
	'% stronger against Neutral',
	'AGI %',
	'ASPD',
	'ASPD %',
	'ATK %',
	'ATK UP (AGI %)',
	'ATK UP (STR %)',
	'Absolute Dodge %',
	'Accuracy',
	'Accuracy %',
	'Additional Melee %',
	'Adds 1 slot to a 0-slotted Bow',
	'Adds 1 slot to a 0-slotted Bowgun',
	'Adds 1 slot to a 0-slotted Halberd',
	'Adds 1 slot to a 0-slotted Knuckle',
	'Adds 1 slot to a 0-slotted Magic Device',
	'Adds 1 slot to a 0-slotted One-Hand Sword',
	'Adds 1 slot to a 0-slotted Staff',
	'Adds 1 slot to a 0-slotted Two-Hand Sword',
	'Adds 1 slot to a 0-slotted additional gear',
	'Adds 1 slot to a 0-slotted body armor',
	'Adds 1 slot to a 0-slotted special gear',
	'Adds 1 slot to a 1-slotted bow',
	'Adds 1 slot to a 1-slotted bowgun',
	'Adds 1 slot to a 1-slotted halberd',
	'Adds 1 slot to a 1-slotted knuckles',
	'Adds 1 slot to a 1-slotted magic device',
	'Adds 1 slot to a 1-slotted one-handed sword',
	'Adds 1 slot to a 1-slotted staff',
	'Adds 1 slot to a 1-slotted two-handed sword',
	'Adds 1 slot to a 1-slotted weapon',
	'Aggro %',
	'Ailment Resistance %',
	'Anticipate %',
	'Attack MP Recovery',
	'Barrier Cooldown %',
	'CSPD',
	'CSPD %',
	'Critical Damage',
	'Critical Damage %',
	'Critical Rate',
	'Critical Rate %',
	'DEX %',
	'Dodge',
	'Dodge %',
	'Drop Rate %',
	'EXP Gain %',
	'Evasion Recharge %',
	'Fire resistance %',
	'Fractional Barrier %',
	'Guard Break %',
	'Guard Power %',
	'Guard Recharge %',
	'INT %',
	'Invincible Aid (sec)',
	'Light Resistance',
	'Light resistance %',
	'Long Range Damage %',
	'MATK %',
	'MATK UP (AGI %)',
	'MATK UP (INT %)',
	'Magic Pierce %',
	'Magic Resistance %',
	'Mana Element',
	'MaxHP',
	'MaxHP %',
	'MaxMP',
	'Motion Speed %',
	'Neutral Resistance %',
	'Physical Pierce %',
	'Physical Resistance %',
	'Reduce Dmg (Bowling) %',
	'Revive Time %',
	'STR %',
	'Short Range Damage %',
	'Stability %',
	'Stun Unavailable',
	'Tumble Unavailable',
	'Unsheathe Attack %',
	'Water Element',
	'Weapon ATK',
	'Weapon ATK %'
];
